name: bonyeza_kazi
description: "Bonyeza Kazi is a job based service where -: Users are able to
  identify labourers such as Plumbers, electricians and/ or cleaning ladies etc.
  Identify professions workers such as event organisers, tailors, mechanics etc.
  There are 2 parties involved: 1) The party providing the service(SP). 2) The
  party asking for the service(Client)."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent: ^0.3.6+12
  animation_director: ^0.1.1
  animations: ^1.1.2
  auto_route: ^0.6.7
  cached_network_image: ^2.3.1
  carousel_slider: ^2.2.1
  cloud_firestore: ^0.14.0+2
  contacts_service: ^0.3.10
  country_code_picker: ^1.4.0
  cupertino_icons: ^0.1.3
  dart_random_choice: ^0.0.2
  dartz: ^0.9.1
  date_time_picker: ^1.0.1
  dio: ^3.0.10
  dio_http_cache: ^0.2.6
  division: ^0.8.8
  dropdown_search: ^0.4.4
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.4
  flutter_google_places: ^0.2.6
  flutter_open_whatsapp: ^0.1.2
  flutter_secure_storage: ^3.3.3
  flutter_svg: ^0.19.0
  flutter_webview_plugin: ^0.3.11
  form_field_validator: ^1.0.1
  flutter_polyline_points: ^0.2.4
  freezed_annotation: ^0.11.0+1
  geocoding: ^1.0.5
  google_maps_flutter: ^0.5.31
  google_maps_webservice: ^0.0.18
  icon_font_generator: ^1.0.0
  image_picker: ^0.6.7+7
  injectable: ^1.0.4
  jiffy: ^3.0.1
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  latlong: ^0.6.1
  line_awesome_flutter: ^1.0.1
  loading_indicator: ^1.2.0
  location: ^3.0.2
  meta: ^1.1.8
  multi_image_picker: ^4.7.14
  page_view_indicators: ^1.4.0
  permission_handler: ^5.0.0
  persistent_bottom_nav_bar: ^2.0.5
  photo_view: ^0.9.2
  responsive_framework: ^0.0.8
  responsive_widgets: ^2.0.1
  rx_shared_preferences: ^1.3.1
  rxdart: ^0.24.1
  share: ^0.6.4+3
  shared_preferences: ^0.5.10
  smart_form: ^0.0.3
  smooth_star_rating: 1.1.1
  tab_indicator_styler: ^1.0.0
  uuid: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8

  build_runner: ^1.10.2
  device_preview: ^0.4.8
  freezed: ^0.11.6
  injectable_generator: ^1.0.4
  json_serializable: ^3.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/electrician.jpg
    - assets/images/builder.jpg
    - assets/images/NYAKUA.png
    - assets/icons/plumbing.svg

  fonts:
    - family: UiIcons
      fonts:
        - asset: assets/iconfont/ui_icons.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/iconfont/MyFlutterApp.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Black.otf
          weight: 900
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Heavy.otf
          weight: 800
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Medium.otf
          weight: 500
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Book.otf
          weight: 400
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Light.otf
          weight: 300

    - family: AvenirRound
      fonts:
        - asset: assets/fonts/Avenir_Next_Round/AvenirNextRoundedProBold.ttf
          weight: 700
        - asset: assets/fonts/Avenir_Next_Round/AvenirNextRoundedProDemi.ttf
          weight: 600
        - asset: assets/fonts/Avenir_Next_Round/AvenirNextRoundedProMedium.ttf
          weight: 500
        - asset: assets/fonts/Avenir_Next_Round/AvenirNextRoundedProRegular.ttf
          weight: 400
